extends RefCounted

static func get_entries() -> Array[Dictionary]:
	return [
		{
			"id": "glass_rail",
			"name": "Glass Rail",
			"summary": "Fragile precision tank with piercing speed and crit pressure.",
			"speed_multiplier": 1.12,
			"health_bonus": -4,
			"damage_multiplier": 1.18,
			"fire_interval_multiplier": 1.08,
			"piercing_level": 1,
			"targeting_array_level": 1,
			"passive_powers": {"ion_lance": 1},
			"color": Color(0.72, 0.92, 1.0, 1.0),
		},
		{
			"id": "bulldozer",
			"name": "Bulldozer",
			"summary": "Close-contact brawler with heavy armor and ram damage but poor tempo.",
			"speed_multiplier": 0.78,
			"health_bonus": 12,
			"damage_multiplier": 1.04,
			"fire_interval_multiplier": 1.16,
			"armor_level": 3,
			"barbed_wire_level": 2,
			"passive_powers": {"bulldozer_aura": 1},
			"color": Color(0.88, 0.78, 0.56, 1.0),
		},
		{
			"id": "swarm_broker",
			"name": "Swarm Broker",
			"summary": "Pet commander with drones and soldiers but weaker personal cannon damage.",
			"speed_multiplier": 0.96,
			"health_bonus": 1,
			"damage_multiplier": 0.88,
			"footsoldier_level": 1,
			"drone_swarm_level": 1,
			"extra_upgrades": {"drone_command": 1},
			"passive_powers": {"pulse_drone": 1},
			"color": Color(0.42, 1.0, 0.66, 1.0),
		},
		{
			"id": "sapper",
			"name": "Sapper",
			"summary": "Trap specialist that starts with dense mine control and bigger explosions.",
			"speed_multiplier": 0.9,
			"health_bonus": 3,
			"damage_multiplier": 0.98,
			"landmine_level": 2,
			"splash_level": 1,
			"extra_upgrades": {"mine_dispenser": 1},
			"passive_powers": {"meteor_shell": 1},
			"color": Color(1.0, 0.66, 0.28, 1.0),
		},
		{
			"id": "chrono_tank",
			"name": "Chrono Tank",
			"summary": "Late-control starter with time bursts, low health, and strong ability scaling.",
			"speed_multiplier": 1.02,
			"health_bonus": -3,
			"damage_multiplier": 0.94,
			"chrono_burst_level": 1,
			"freeze_pulse_level": 1,
			"extra_upgrades": {"field_amplifier": 1},
			"passive_powers": {"time_shock": 1},
			"color": Color(0.64, 0.62, 1.0, 1.0),
		},
		{
			"id": "gold_engine",
			"name": "Gold Engine",
			"summary": "Greedy economy tank with huge scaling potential and weaker early damage.",
			"speed_multiplier": 1.0,
			"health_bonus": -2,
			"damage_multiplier": 0.86,
			"exp_bonus_level": 2,
			"magnet_level": 1,
			"passive_powers": {"golden_reactor": 1, "supply_beacon": 1},
			"color": Color(1.0, 0.86, 0.32, 1.0),
		},
		{
			"id": "rift_skimmer",
			"name": "Rift Skimmer",
			"summary": "Extremely fast control tank with weak armor and strong pickup reach.",
			"speed_multiplier": 1.36,
			"health_bonus": -5,
			"damage_multiplier": 0.9,
			"magnet_level": 2,
			"gravity_well_level": 1,
			"passive_powers": {"phase_magnet": 1},
			"color": Color(0.95, 0.48, 1.0, 1.0),
		},
		{
			"id": "fortress_medic",
			"name": "Fortress Medic",
			"summary": "Slow sustain fortress with repairs, armor, and low burst damage.",
			"speed_multiplier": 0.74,
			"health_bonus": 14,
			"damage_multiplier": 0.9,
			"armor_level": 2,
			"regeneration_level": 2,
			"repair_beacon_level": 1,
			"passive_powers": {"guardian_wall": 1, "repair_burst": 1},
			"color": Color(0.62, 1.0, 0.86, 1.0),
		},
		{
			"id": "meteor_twins",
			"name": "Meteor Twins",
			"summary": "Double-barrel explosive tank that scales through multishot and blast synergies.",
			"speed_multiplier": 0.94,
			"health_bonus": 0,
			"damage_multiplier": 0.96,
			"fire_interval_multiplier": 1.04,
			"cannon_level": 2,
			"splash_level": 1,
			"passive_powers": {"orbital_cannon": 1},
			"color": Color(1.0, 0.45, 0.24, 1.0),
		},
		{
			"id": "storm_foundry",
			"name": "Storm Foundry",
			"summary": "Heavy electric factory that starts slow but stacks power damage quickly.",
			"speed_multiplier": 0.86,
			"health_bonus": 6,
			"damage_multiplier": 1.02,
			"shock_field_level": 1,
			"tesla_pylon_level": 1,
			"capacitor_bank_level": 1,
			"passive_powers": {"storm_catalyst": 1},
			"color": Color(0.28, 0.78, 1.0, 1.0),
		},
		{
			"id": "prism_sentinel",
			"name": "Prism Sentinel",
			"summary": "Crystal precision tank that opens with ricochets, crit scaling, and piercing angles.",
			"speed_multiplier": 1.06,
			"health_bonus": -2,
			"damage_multiplier": 1.08,
			"fire_interval_multiplier": 1.06,
			"piercing_level": 1,
			"targeting_array_level": 1,
			"ricochet_rounds_level": 1,
			"extra_upgrades": {"crystal_lens": 1, "prism_rounds": 1},
			"passive_powers": {"critical_storm": 1},
			"color": Color(0.64, 0.94, 1.0, 1.0),
		},
		{
			"id": "void_anchor",
			"name": "Void Anchor",
			"summary": "Heavy gravity bruiser that sacrifices tempo for black-hole control and crush damage.",
			"speed_multiplier": 0.8,
			"health_bonus": 10,
			"damage_multiplier": 1.12,
			"fire_interval_multiplier": 1.14,
			"gravity_well_level": 2,
			"armor_level": 1,
			"barbed_wire_level": 1,
			"extra_upgrades": {"gravity_anchor": 1, "singularity_lens": 1},
			"passive_powers": {"black_hole_mines": 1, "fortress_protocol": 1},
			"color": Color(0.58, 0.46, 0.92, 1.0),
		},
		{
			"id": "neon_courier",
			"name": "Neon Courier",
			"summary": "Late-grid runner with extreme mobility, supply tools, and fragile overdrive tempo.",
			"speed_multiplier": 1.32,
			"health_bonus": -4,
			"damage_multiplier": 0.92,
			"fire_interval_multiplier": 0.94,
			"overdrive_core_level": 1,
			"magnet_level": 2,
			"extra_upgrades": {"vector_thrusters": 1, "kinetic_treads": 1, "salvage_magnet": 1},
			"passive_powers": {"phase_magnet": 1, "supply_beacon": 1},
			"color": Color(0.2, 1.0, 0.92, 1.0),
		},
		{
			"id": "bloom_artillerist",
			"name": "Bloom Artillerist",
			"summary": "Postgame siege tank with slow movement, heavy ordnance, and layered artillery payoffs.",
			"speed_multiplier": 0.76,
			"health_bonus": 4,
			"damage_multiplier": 1.1,
			"fire_interval_multiplier": 1.1,
			"artillery_level": 1,
			"missile_pod_level": 1,
			"splash_level": 1,
			"extra_upgrades": {"ordnance_bay": 1, "munition_printer": 1, "impact_fuse": 1},
			"passive_powers": {"orbital_cannon": 1, "munition_swarm": 1},
			"color": Color(0.54, 1.0, 0.58, 1.0),
		},
		{
			"id": "gear_oracle",
			"name": "Gear Oracle",
			"summary": "Clockwork postgame tank with slow movement, precision beams, tempo control, and rich boss payouts.",
			"speed_multiplier": 0.82,
			"health_bonus": 2,
			"damage_multiplier": 1.06,
			"fire_interval_multiplier": 0.96,
			"piercing_level": 1,
			"targeting_array_level": 2,
			"railgun_orbiter_level": 1,
			"tesla_pylon_level": 1,
			"chrono_burst_level": 1,
			"extra_upgrades": {"target_predictor": 1, "weakpoint_scanner": 1, "capacitor_mesh": 1},
			"passive_powers": {"time_shock": 1, "storm_catalyst": 1, "golden_reactor": 1},
			"color": Color(0.94, 0.72, 0.28, 1.0),
		}
	]
