extends RefCounted

static func get_entries() -> Array[Dictionary]:
	return [
		{
			"id": "map6",
			"name": "Moonlit Graveyard",
			"summary": "A dark, wide arena with tombstone corridors, lower visibility mood, spectral bosses, and periodic ghost surges.",
			"spawn_interval_multiplier": 0.47,
			"boss_spawn_interval_multiplier": 0.46,
			"enemy_speed_growth_multiplier": 1.45,
			"enemy_health_growth_multiplier": 1.62,
			"enemy_damage_growth_multiplier": 1.42,
			"active_enemy_cap_bonus": 145,
			"active_enemy_cap_limit": 360,
			"elite_chance_multiplier": 2.2,
			"map_gimmick": "ghost_surge",
			"gimmick_interval": 12.0,
			"mood_color": Color(0.58, 0.62, 0.82, 1.0),
			"background_texture": "res://assets/backgrounds/map6_moonlit_graveyard.png",
		},
		{
			"id": "map7",
			"name": "Neon Grid",
			"summary": "A bright rectangular combat grid with lane blockers, speed pressure, and periodic laser lattice hazards.",
			"spawn_interval_multiplier": 0.43,
			"boss_spawn_interval_multiplier": 0.42,
			"enemy_speed_growth_multiplier": 1.65,
			"enemy_health_growth_multiplier": 1.5,
			"enemy_damage_growth_multiplier": 1.46,
			"active_enemy_cap_bonus": 160,
			"active_enemy_cap_limit": 380,
			"elite_chance_multiplier": 2.35,
			"map_gimmick": "laser_lattice",
			"gimmick_interval": 10.0,
			"mood_color": Color(0.72, 0.9, 1.0, 1.0),
			"background_texture": "res://assets/backgrounds/map7_neon_grid.png",
		},
		{
			"id": "map8",
			"name": "Frozen Scar",
			"summary": "A long frozen battlefield with ice ridges, tanky enemy growth, and recurring frost locks around the player.",
			"spawn_interval_multiplier": 0.4,
			"boss_spawn_interval_multiplier": 0.39,
			"enemy_speed_growth_multiplier": 1.28,
			"enemy_health_growth_multiplier": 1.88,
			"enemy_damage_growth_multiplier": 1.52,
			"active_enemy_cap_bonus": 175,
			"active_enemy_cap_limit": 395,
			"elite_chance_multiplier": 2.5,
			"map_gimmick": "frost_lock",
			"gimmick_interval": 14.0,
			"mood_color": Color(0.78, 0.94, 1.0, 1.0),
			"background_texture": "res://assets/backgrounds/map8_frozen_scar.png",
		},
		{
			"id": "map9",
			"name": "Ember Rift",
			"summary": "A compact lava arena with pressure funnels, brutal boss cadence, and eruption hazards.",
			"spawn_interval_multiplier": 0.36,
			"boss_spawn_interval_multiplier": 0.34,
			"enemy_speed_growth_multiplier": 1.52,
			"enemy_health_growth_multiplier": 1.95,
			"enemy_damage_growth_multiplier": 1.72,
			"active_enemy_cap_bonus": 190,
			"active_enemy_cap_limit": 410,
			"elite_chance_multiplier": 2.75,
			"map_gimmick": "ember_eruption",
			"gimmick_interval": 9.0,
			"mood_color": Color(1.0, 0.72, 0.56, 1.0),
			"background_texture": "res://assets/backgrounds/map9_ember_rift.png",
		},
		{
			"id": "map10",
			"name": "Astral Engine",
			"summary": "Final massive arena with broken engine walls, extreme mixed pressure, and alternating astral collapse waves.",
			"spawn_interval_multiplier": 0.32,
			"boss_spawn_interval_multiplier": 0.3,
			"enemy_speed_growth_multiplier": 1.72,
			"enemy_health_growth_multiplier": 2.15,
			"enemy_damage_growth_multiplier": 1.86,
			"active_enemy_cap_bonus": 220,
			"active_enemy_cap_limit": 450,
			"elite_chance_multiplier": 3.1,
			"map_gimmick": "astral_collapse",
			"gimmick_interval": 8.0,
			"mood_color": Color(0.88, 0.82, 1.0, 1.0),
			"background_texture": "res://assets/backgrounds/map10_astral_engine.png",
		}
	]
