extends RefCounted


static func get_entries(boss_scene: PackedScene) -> Array[Dictionary]:
	return [
		{"id": "grave_bell", "maps": ["map6"], "scene": boss_scene, "unlock_seconds": 0.0, "weight": 118.0, "growth_per_minute": -0.6, "min_weight": 70.0, "max_weight": 118.0, "health": 6200, "speed": 24.0, "contact_damage": 18, "exp_drop_count": 92, "exp_drop_min_tier": 4, "color": Color(0.46, 0.52, 0.88, 1.0), "scale": 1.28, "behavior": "wraith", "texture": "res://assets/visual/enemies/variants/enemy_orbiter_cartoon.png", "phase_thresholds": [0.74, 0.48, 0.22], "ability_modules": [{"type": "target_hazard", "cooldown": 3.8, "initial_delay": 1.4, "radius": 64.0, "damage": 6}, {"type": "minion_call", "cooldown": 6.0, "initial_delay": 3.5, "count": 4, "phase_count_bonus": 2}]},
		{"id": "crypt_marshal", "maps": ["map6"], "scene": boss_scene, "unlock_seconds": 480.0, "weight": 92.0, "growth_per_minute": 2.2, "min_weight": 0.0, "max_weight": 128.0, "health": 8200, "speed": 18.0, "contact_damage": 22, "exp_drop_count": 122, "exp_drop_min_tier": 4, "color": Color(0.28, 0.3, 0.56, 1.0), "scale": 1.55, "behavior": "bastion", "texture": "res://assets/visual/enemies/variants/enemy_tank_cartoon.png", "phase_thresholds": [0.82, 0.64, 0.42, 0.2], "ability_modules": [{"type": "hazard_ring", "cooldown": 5.2, "initial_delay": 2.0, "count": 9, "phase_count_bonus": 2, "radius": 72.0, "ring_distance": 190.0, "damage": 6}, {"type": "minion_call", "cooldown": 7.2, "initial_delay": 4.8, "count": 5, "phase_count_bonus": 2}]},
		{"id": "neon_executioner", "maps": ["map7"], "scene": boss_scene, "unlock_seconds": 0.0, "weight": 120.0, "growth_per_minute": -0.8, "min_weight": 72.0, "max_weight": 120.0, "health": 6500, "speed": 42.0, "contact_damage": 19, "exp_drop_count": 98, "exp_drop_min_tier": 4, "color": Color(0.06, 0.92, 1.0, 1.0), "scale": 1.02, "behavior": "tempest", "texture": "res://assets/visual/enemies/variants/enemy_zigzag_cartoon.png", "phase_thresholds": [0.7, 0.42, 0.18], "ability_modules": [{"type": "target_hazard", "cooldown": 3.2, "initial_delay": 1.1, "radius": 54.0, "damage": 6}, {"type": "hazard_ring", "cooldown": 5.0, "initial_delay": 3.0, "count": 7, "phase_count_bonus": 1, "radius": 50.0, "ring_distance": 170.0, "damage": 5}]},
		{"id": "grid_overseer", "maps": ["map7"], "scene": boss_scene, "unlock_seconds": 540.0, "weight": 90.0, "growth_per_minute": 2.5, "min_weight": 0.0, "max_weight": 132.0, "health": 9000, "speed": 28.0, "contact_damage": 23, "exp_drop_count": 130, "exp_drop_min_tier": 4, "color": Color(0.95, 0.25, 1.0, 1.0), "scale": 1.34, "behavior": "overlord", "texture": "res://assets/visual/enemies/variants/enemy_reaper_cartoon.png", "phase_thresholds": [0.78, 0.56, 0.34, 0.14], "ability_modules": [{"type": "hazard_ring", "cooldown": 4.6, "initial_delay": 1.6, "count": 10, "phase_count_bonus": 1, "radius": 62.0, "ring_distance": 205.0, "damage": 6}, {"type": "target_hazard", "cooldown": 4.0, "initial_delay": 4.0, "radius": 66.0, "damage": 7}]},
		{"id": "frost_leviathan", "maps": ["map8"], "scene": boss_scene, "unlock_seconds": 0.0, "weight": 118.0, "growth_per_minute": -0.4, "min_weight": 74.0, "max_weight": 118.0, "health": 9800, "speed": 18.0, "contact_damage": 24, "exp_drop_count": 112, "exp_drop_min_tier": 4, "color": Color(0.64, 0.92, 1.0, 1.0), "scale": 1.62, "behavior": "crusher", "texture": "res://assets/visual/enemies/variants/enemy_tank_cartoon.png", "phase_thresholds": [0.8, 0.58, 0.36, 0.16], "ability_modules": [{"type": "hazard_ring", "cooldown": 5.4, "initial_delay": 2.0, "count": 8, "phase_count_bonus": 2, "radius": 76.0, "ring_distance": 220.0, "damage": 7}]},
		{"id": "blizzard_matriarch", "maps": ["map8"], "scene": boss_scene, "unlock_seconds": 600.0, "weight": 86.0, "growth_per_minute": 2.4, "min_weight": 0.0, "max_weight": 130.0, "health": 8600, "speed": 34.0, "contact_damage": 21, "exp_drop_count": 136, "exp_drop_min_tier": 4, "color": Color(0.38, 0.76, 1.0, 1.0), "scale": 1.22, "behavior": "monarch", "texture": "res://assets/visual/enemies/variants/enemy_drifter_cartoon.png", "phase_thresholds": [0.76, 0.52, 0.28], "ability_modules": [{"type": "minion_call", "cooldown": 5.4, "initial_delay": 2.2, "count": 5, "phase_count_bonus": 2}, {"type": "target_hazard", "cooldown": 4.4, "initial_delay": 4.0, "radius": 68.0, "damage": 6}]},
		{"id": "magma_tyrant", "maps": ["map9"], "scene": boss_scene, "unlock_seconds": 0.0, "weight": 122.0, "growth_per_minute": -0.5, "min_weight": 76.0, "max_weight": 122.0, "health": 10400, "speed": 30.0, "contact_damage": 28, "exp_drop_count": 126, "exp_drop_min_tier": 4, "color": Color(1.0, 0.22, 0.06, 1.0), "scale": 1.46, "behavior": "overlord", "texture": "res://assets/visual/enemies/variants/enemy_reaper_cartoon.png", "phase_thresholds": [0.82, 0.62, 0.42, 0.18], "ability_modules": [{"type": "target_hazard", "cooldown": 3.6, "initial_delay": 1.2, "radius": 74.0, "damage": 8}, {"type": "hazard_ring", "cooldown": 4.8, "initial_delay": 3.0, "count": 9, "phase_count_bonus": 2, "radius": 70.0, "ring_distance": 185.0, "damage": 7}]},
		{"id": "cinder_prophet", "maps": ["map9"], "scene": boss_scene, "unlock_seconds": 520.0, "weight": 92.0, "growth_per_minute": 2.7, "min_weight": 0.0, "max_weight": 136.0, "health": 7800, "speed": 46.0, "contact_damage": 22, "exp_drop_count": 142, "exp_drop_min_tier": 4, "color": Color(1.0, 0.62, 0.12, 1.0), "scale": 1.05, "behavior": "sprinter", "texture": "res://assets/visual/enemies/variants/enemy_runner_cartoon.png", "phase_thresholds": [0.68, 0.38, 0.16], "ability_modules": [{"type": "target_hazard", "cooldown": 3.0, "initial_delay": 1.0, "radius": 56.0, "damage": 7}, {"type": "minion_call", "cooldown": 5.6, "initial_delay": 3.5, "count": 4, "phase_count_bonus": 2}]},
		{"id": "astral_archon", "maps": ["map10"], "scene": boss_scene, "unlock_seconds": 0.0, "weight": 124.0, "growth_per_minute": -0.2, "min_weight": 82.0, "max_weight": 124.0, "health": 11200, "speed": 38.0, "contact_damage": 30, "exp_drop_count": 150, "exp_drop_min_tier": 4, "color": Color(0.68, 0.42, 1.0, 1.0), "scale": 1.34, "behavior": "singularity", "texture": "res://assets/visual/enemies/variants/enemy_zigzag_cartoon.png", "phase_thresholds": [0.86, 0.68, 0.5, 0.32, 0.14], "ability_modules": [{"type": "hazard_ring", "cooldown": 4.2, "initial_delay": 1.3, "count": 11, "phase_count_bonus": 2, "radius": 66.0, "ring_distance": 210.0, "damage": 8}, {"type": "target_hazard", "cooldown": 3.4, "initial_delay": 2.8, "radius": 72.0, "damage": 8}, {"type": "minion_call", "cooldown": 5.2, "initial_delay": 4.6, "count": 6, "phase_count_bonus": 2}]},
		{"id": "engine_heart", "maps": ["map10"], "scene": boss_scene, "unlock_seconds": 660.0, "weight": 96.0, "growth_per_minute": 2.8, "min_weight": 0.0, "max_weight": 144.0, "health": 14800, "speed": 20.0, "contact_damage": 34, "exp_drop_count": 180, "exp_drop_min_tier": 4, "color": Color(0.18, 0.96, 1.0, 1.0), "scale": 1.72, "behavior": "bastion", "texture": "res://assets/visual/enemies/variants/enemy_tank_cartoon.png", "phase_thresholds": [0.88, 0.72, 0.56, 0.4, 0.24, 0.1], "ability_modules": [{"type": "hazard_ring", "cooldown": 4.0, "initial_delay": 1.4, "count": 12, "phase_count_bonus": 2, "radius": 80.0, "ring_distance": 240.0, "damage": 9}, {"type": "minion_call", "cooldown": 4.8, "initial_delay": 3.8, "count": 7, "phase_count_bonus": 2}]},
	]
