extends RefCounted


static func get_entries() -> Dictionary:
	return {
	"speed": {"title": "+ SPEED", "tag": "MOBILITY", "hint": "Raises tank movement speed.", "synergy": ["magnet", "oil_slick_level"]},
	"fire_rate": {"title": "+ FIRE RATE", "tag": "WEAPON", "hint": "Reduces cannon cooldown so the tank shoots more often.", "synergy": ["damage", "cannon", "footsoldier_level", "drone_swarm_level"]},
	"damage": {"title": "+ DAMAGE", "tag": "WEAPON", "hint": "Raises main cannon damage.", "synergy": ["fire_rate", "splash", "piercing", "shock_field_level"]},
	"regeneration": {"title": "+ REGENERATION", "tag": "SUSTAIN", "hint": "Repairs the tank slowly over time.", "synergy": ["armor", "barbed_wire"]},
	"exp": {"title": "+ EXP VALUE", "tag": "ECONOMY", "hint": "Makes every EXP crystal worth more.", "synergy": ["magnet"]},
	"splash": {"title": "+ SPLASH", "tag": "AREA", "hint": "Adds an explosion radius to cannon shells.", "synergy": ["damage", "piercing", "artillery_level", "landmine_level"]},
	"piercing": {"title": "+ PIERCING", "tag": "CLEAR", "hint": "Lets cannon shells hit additional enemies before disappearing.", "synergy": ["damage", "splash", "fire_rate"]},
	"barbed_wire": {"title": "+ BARBED WIRE", "tag": "CONTACT", "hint": "Creates a close-range damage ring around the tank.", "synergy": ["armor", "regeneration", "shock_field_level"]},
	"armor": {"title": "+ ARMOR", "tag": "DEFENSE", "hint": "Reduce incoming hit damage.", "synergy": ["barbed_wire", "regeneration", "circular_saw_level"]},
	"magnet": {"title": "+ MAGNET", "tag": "ECONOMY", "hint": "Pull EXP from farther away.", "synergy": ["exp", "speed", "artillery_level"]},
	"cannon": {"title": "+ MULTISHOT", "tag": "MULTISHOT", "hint": "Adds another shell to each cannon volley.", "synergy": ["damage", "fire_rate", "drone_swarm_level"]},
	"targeting_array": {"title": "+ TARGETING ARRAY", "tag": "ACCESSORY", "hint": "Adds stacking critical hit chance.", "synergy": ["damage", "fire_rate", "cannon"]},
	"accelerator": {"title": "+ ACCELERATOR", "tag": "ACCESSORY", "hint": "Shots travel faster and reach targets sooner.", "synergy": ["piercing", "splash", "payload_rack"]},
	"alloy_plating": {"title": "+ ALLOY PLATING", "tag": "ACCESSORY", "hint": "Raises max health and repairs some HP.", "synergy": ["armor", "regeneration", "reactive_shield"]},
	"recycler": {"title": "+ RECYCLER", "tag": "ACCESSORY", "hint": "Defeated enemies can repair the tank.", "synergy": ["magnet", "exp", "alloy_plating"]},
	"payload_rack": {"title": "+ PAYLOAD RACK", "tag": "ACCESSORY", "hint": "Adds payload blast radius and splash damage.", "synergy": ["splash", "damage", "accelerator"]},
	"reactive_shield": {"title": "+ REACTIVE SHIELD", "tag": "ACCESSORY", "hint": "Extends post-hit invulnerability windows.", "synergy": ["armor", "alloy_plating", "recycler"]},
	"gyro_stabilizer": {"title": "+ GYRO STABILIZER", "tag": "CONTROL", "hint": "Rotate faster and acquire targets sooner.", "synergy": ["fire_rate", "cannon", "accelerator"]},
	"rapid_loader": {"title": "+ RAPID LOADER", "tag": "WEAPON", "hint": "Slightly lowers fire interval.", "synergy": ["fire_rate", "damage", "ammo_synthesizer"]},
	"high_caliber": {"title": "+ HIGH CALIBER", "tag": "POWER", "hint": "Raises damage and projectile size.", "synergy": ["damage", "targeting_array", "piercing"]},
	"nanobots": {"title": "+ NANOBOTS", "tag": "SUSTAIN", "hint": "Increases all healing received.", "synergy": ["regeneration", "recycler", "emergency_repairs"]},
	"kinetic_treads": {"title": "+ KINETIC TREADS", "tag": "MOBILITY", "hint": "Adds another movement speed multiplier.", "synergy": ["speed", "oil_slick_level", "magnet"]},
	"ammo_synthesizer": {"title": "+ AMMO SYNTH", "tag": "MULTISHOT", "hint": "Adds alternating extra shots to volleys.", "synergy": ["cannon", "rapid_loader", "damage"]},
	"shatter_rounds": {"title": "+ SHATTER ROUNDS", "tag": "AREA", "hint": "Adds splash radius and splash damage.", "synergy": ["splash", "payload_rack", "combustion_mix"]},
	"phase_core": {"title": "+ PHASE CORE", "tag": "CLEAR", "hint": "Adds projectile speed and periodic piercing.", "synergy": ["piercing", "accelerator", "high_caliber"]},
	"capacitor_bank": {"title": "+ CAPACITOR BANK", "tag": "POWER", "hint": "Amplifies weapon and power damage.", "synergy": ["damage", "overdrive_core_level", "chain_lightning_level"]},
	"salvage_magnet": {"title": "+ SALVAGE MAGNET", "tag": "ECONOMY", "hint": "Boosts EXP value and pickup pull radius.", "synergy": ["magnet", "exp", "recycler"]},
	"emergency_repairs": {"title": "+ EMERGENCY REPAIRS", "tag": "SUSTAIN", "hint": "Repairs the tank while critically damaged.", "synergy": ["armor", "nanobots", "reactive_shield"]},
	"combustion_mix": {"title": "+ COMBUSTION MIX", "tag": "AREA", "hint": "Raises splash and contact-area damage.", "synergy": ["splash", "barbed_wire", "landmine_level"]},
	"heat_sinks": {"title": "+ HEAT SINKS", "tag": "TEMPO", "hint": "Lowers firing interval without adding shots.", "synergy": ["fire_rate", "overdrive_core_level", "railgun_orbiter_level"]},
	"overclocked_barrel": {"title": "+ OVERCLOCKED BARREL", "tag": "WEAPON", "hint": "Raises damage while slightly lowering fire interval.", "synergy": ["damage", "rapid_loader", "heat_sinks"]},
	"rail_stabilizer": {"title": "+ RAIL STABILIZER", "tag": "PRECISION", "hint": "Adds crit chance and boosts Railgun Orbiter levels.", "synergy": ["targeting_array", "railgun_orbiter_level", "accelerator"]},
	"missile_guidance": {"title": "+ MISSILE GUIDANCE", "tag": "AREA", "hint": "Boosts Missile Pod levels and adds blast radius.", "synergy": ["missile_pod_level", "payload_rack", "ordnance_bay"]},
	"ordnance_bay": {"title": "+ ORDNANCE BAY", "tag": "AREA", "hint": "Raises splash radius, splash damage, and siege power levels.", "synergy": ["splash", "artillery_level", "missile_pod_level"]},
	"field_amplifier": {"title": "+ FIELD AMPLIFIER", "tag": "AURA", "hint": "Boosts aura and field powers every two levels.", "synergy": ["shock_field_level", "flame_wave_level", "gravity_well_level"]},
	"volt_coils": {"title": "+ VOLT COILS", "tag": "POWER", "hint": "Boosts electric powers and power damage.", "synergy": ["chain_lightning_level", "shock_field_level", "capacitor_bank"]},
	"gravity_anchor": {"title": "+ GRAVITY ANCHOR", "tag": "CONTROL", "hint": "Boosts Gravity Well and area damage.", "synergy": ["gravity_well_level", "combustion_mix", "barbed_wire"]},
	"repair_drones": {"title": "+ REPAIR DRONES", "tag": "SUSTAIN", "hint": "Improves healing and Repair Beacon level.", "synergy": ["repair_beacon_level", "nanobots", "recycler"]},
	"crystal_lens": {"title": "+ CRYSTAL LENS", "tag": "ECONOMY", "hint": "Adds EXP value and crit chance.", "synergy": ["exp", "salvage_magnet", "targeting_array"]},
	"munition_printer": {"title": "+ MUNITION PRINTER", "tag": "MULTISHOT", "hint": "Adds periodic extra shots to volleys.", "synergy": ["cannon", "ammo_synthesizer", "ordnance_bay"]},
	"stabilized_chassis": {"title": "+ STABILIZED CHASSIS", "tag": "DEFENSE", "hint": "Adds armor reduction and rotation control.", "synergy": ["armor", "gyro_stabilizer", "reactive_shield"]},
	"vector_thrusters": {"title": "+ VECTOR THRUSTERS", "tag": "MOBILITY", "hint": "Boosts movement, rotation, and projectile speed.", "synergy": ["speed", "accelerator", "kinetic_treads"]},
	"impact_fuse": {"title": "+ IMPACT FUSE", "tag": "AREA", "hint": "Adds blast radius and splash damage.", "synergy": ["splash", "shatter_rounds", "ordnance_bay"]},
	"armor_piercers": {"title": "+ ARMOR PIERCERS", "tag": "CLEAR", "hint": "Adds projectile damage and periodic pierce.", "synergy": ["piercing", "phase_core", "weakpoint_scanner"]},
	"weakpoint_scanner": {"title": "+ WEAKPOINT SCANNER", "tag": "PRECISION", "hint": "Adds crit power and boosts rail beams.", "synergy": ["targeting_array", "rail_stabilizer", "railgun_orbiter_level"]},
	"med_pump": {"title": "+ MED PUMP", "tag": "SUSTAIN", "hint": "Improves healing and emergency repair cadence.", "synergy": ["nanobots", "repair_drones", "emergency_repairs"]},
	"orbit_gears": {"title": "+ ORBIT GEARS", "tag": "CONTACT", "hint": "Boosts orbit contact damage and satellite levels.", "synergy": ["circular_saw_level", "guardian_satellite_level", "barbed_wire"]},
	"mine_dispenser": {"title": "+ MINE DISPENSER", "tag": "DEVICE", "hint": "Places stronger mines more often.", "synergy": ["landmine_level", "combustion_mix", "impact_fuse"]},
	"drone_command": {"title": "+ DRONE COMMAND", "tag": "PET", "hint": "Boosts pet damage and drone-style power levels.", "synergy": ["footsoldier_level", "drone_swarm_level", "guardian_satellite_level"]},
	"lucky_core": {"title": "+ LUCKY CORE", "tag": "LUCK", "hint": "Adds EXP, crit chance, and occasional extra shots.", "synergy": ["crystal_lens", "targeting_array", "munition_printer"]},
	"auto_loader": {"title": "+ AUTO LOADER", "tag": "TEMPO", "hint": "Slightly lowers cannon cooldown.", "synergy": ["fire_rate"]},
	"focus_lens": {"title": "+ FOCUS LENS", "tag": "CRIT", "hint": "Adds crit chance and crit damage after Targeting Array.", "synergy": ["targeting_array"]},
	"reinforced_tracks": {"title": "+ REINFORCED TRACKS", "tag": "DEFENSE", "hint": "Adds armor and a small speed boost.", "synergy": ["speed", "armor"]},
	"field_medic_kit": {"title": "+ FIELD MEDIC KIT", "tag": "SUSTAIN", "hint": "Raises healing received and max health.", "synergy": ["nanobots", "repair_beacon_level"]},
	"repair_gel": {"title": "+ REPAIR GEL", "tag": "SUSTAIN", "hint": "Strongly improves all healing after Nanobots.", "synergy": ["nanobots"]},
	"salvage_claws": {"title": "+ SALVAGE CLAWS", "tag": "SUSTAIN", "hint": "Increases the chance for enemy kills to repair the tank.", "synergy": ["recycler"]},
	"wide_nozzle": {"title": "+ WIDE NOZZLE", "tag": "AREA", "hint": "Expands shell explosion radius.", "synergy": ["splash"]},
	"chain_fuse": {"title": "+ CHAIN FUSE", "tag": "AREA", "hint": "Raises explosion damage.", "synergy": ["splash"]},
	"reactive_tracks": {"title": "+ REACTIVE TRACKS", "tag": "MOBILITY", "hint": "Adds speed and slightly longer safety after being hit.", "synergy": ["speed", "reactive_shield"]},
	"polished_barrel": {"title": "+ POLISHED BARREL", "tag": "WEAPON", "hint": "Raises cannon damage and shell speed.", "synergy": ["damage", "accelerator"]},
	"pickup_scoop": {"title": "+ PICKUP SCOOP", "tag": "ECONOMY", "hint": "Increases pickup reach for crystals and repair items.", "synergy": ["magnet"]},
	"overcharger": {"title": "+ OVERCHARGER", "tag": "POWER", "hint": "Raises ability damage after owning a power.", "synergy": ["shock_field_level", "capacitor_bank"]},
	"boss_buster": {"title": "+ BOSS BUSTER", "tag": "WEAPON", "hint": "Adds damage pressure intended for boss fights.", "synergy": ["damage"]},
	"elite_hunter": {"title": "+ ELITE HUNTER", "tag": "WEAPON", "hint": "Adds damage pressure against dangerous special enemies.", "synergy": ["damage"]},
	"crystal_converter": {"title": "+ CRYSTAL CONVERTER", "tag": "ECONOMY", "hint": "Increases EXP value after taking EXP upgrades.", "synergy": ["exp"]},
	"armor_gasket": {"title": "+ ARMOR GASKET", "tag": "DEFENSE", "hint": "Adds armor and improves healing.", "synergy": ["armor", "nanobots"]},
	"blast_compound": {"title": "+ BLAST COMPOUND", "tag": "AREA", "hint": "Raises explosion radius and explosion damage.", "synergy": ["splash"]},
	"coolant_loop": {"title": "+ COOLANT LOOP", "tag": "TEMPO", "hint": "Slightly lowers cannon cooldown and improves power damage.", "synergy": ["fire_rate", "capacitor_bank"]},
	"recoil_brace": {"title": "+ RECOIL BRACE", "tag": "WEAPON", "hint": "Raises cannon damage and crit chance.", "synergy": ["damage", "targeting_array"]},
	"split_chamber": {"title": "+ SPLIT CHAMBER", "tag": "MULTISHOT", "hint": "Adds a chance to fire one extra shell after taking Multishot.", "synergy": ["cannon"]},
	"power_coupler": {"title": "+ POWER COUPLER", "tag": "POWER", "hint": "Raises ability damage after owning a power.", "synergy": ["shock_field_level"]},
	"shock_absorbers": {"title": "+ SHOCK ABSORBERS", "tag": "DEFENSE", "hint": "Adds armor and slightly longer hit protection.", "synergy": ["armor"]},
	"supply_scanner": {"title": "+ SUPPLY SCANNER", "tag": "ECONOMY", "hint": "Improves pickup reach and EXP value.", "synergy": ["magnet", "exp"]},
	"wrench_arm": {"title": "+ WRENCH ARM", "tag": "SUSTAIN", "hint": "Greatly improves repair pickup reach and healing received.", "synergy": ["magnet", "nanobots"]},
	"battle_vault": {"title": "+ BATTLE VAULT", "tag": "DEFENSE", "hint": "Adds max health and armor.", "synergy": ["armor"]},
	"kinetic_capacitor": {"title": "+ KINETIC CAPACITOR", "tag": "MOBILITY", "hint": "Adds speed and power damage after movement upgrades.", "synergy": ["speed"]},
	"prism_rounds": {"title": "+ PRISM ROUNDS", "tag": "CRIT", "hint": "Adds crit chance and shell speed after Piercing.", "synergy": ["piercing"]},
	"target_link": {"title": "+ TARGET LINK", "tag": "PET", "hint": "Improves crit chance and pet damage after owning a pet.", "synergy": ["footsoldier_level"]},
	"flare_core": {"title": "+ FLARE CORE", "tag": "AREA", "hint": "Improves area and power damage after Flame Wave.", "synergy": ["flame_wave_level"]},
	"lucky_battery": {"title": "+ LUCKY BATTERY", "tag": "LUCK", "hint": "Adds EXP value and occasional extra shells after Lucky Core.", "synergy": ["lucky_core"]},
	"thermal_jacket": {"title": "+ THERMAL JACKET", "tag": "TEMPO", "hint": "Adds armor while slightly improving firing cadence after Fire Rate.", "synergy": ["fire_rate", "armor"]},
	"shrapnel_matrix": {"title": "+ SHRAPNEL MATRIX", "tag": "AREA", "hint": "Raises explosion damage and crit damage after Splash.", "synergy": ["splash", "targeting_array"]},
	"hollow_point_feed": {"title": "+ HOLLOW POINT FEED", "tag": "WEAPON", "hint": "Raises cannon damage and crit damage after Damage.", "synergy": ["damage", "targeting_array"]},
	"engine_supercharger": {"title": "+ ENGINE SUPERCHARGER", "tag": "MOBILITY", "hint": "Boosts tank speed and shell speed after Speed.", "synergy": ["speed", "accelerator"]},
	"field_siphon": {"title": "+ FIELD SIPHON", "tag": "SUSTAIN", "hint": "Improves kill-repair chance and healing after Recycler.", "synergy": ["recycler", "nanobots"]},
	"orbital_prism": {"title": "+ ORBITAL PRISM", "tag": "MULTISHOT", "hint": "Adds extra-shell chance and crit chance after Prism Rounds.", "synergy": ["prism_rounds", "cannon"]},
	"nano_plating": {"title": "+ NANO PLATING", "tag": "DEFENSE", "hint": "Adds armor and stronger repairs after Nanobots.", "synergy": ["nanobots", "armor"]},
	"kinetic_scoop": {"title": "+ KINETIC SCOOP", "tag": "ECONOMY", "hint": "Raises pickup reach and speed after Magnet.", "synergy": ["magnet", "speed"]},
	"capacitor_mesh": {"title": "+ CAPACITOR MESH", "tag": "POWER", "hint": "Raises ability damage and crit chance after Capacitor Bank.", "synergy": ["capacitor_bank", "targeting_array"]},
	"drone_uplink": {"title": "+ DRONE UPLINK", "tag": "PET", "hint": "Improves pet damage and projectile damage after Drone Command.", "synergy": ["drone_command", "footsoldier_level"]},
	"blast_retainer": {"title": "+ BLAST RETAINER", "tag": "AREA", "hint": "Adds blast radius, blast damage, and area damage after Splash.", "synergy": ["splash", "combustion_mix"]},
	"mender_tracks": {"title": "+ MENDER TRACKS", "tag": "SUSTAIN", "hint": "Adds speed and healing after Field Medic Kit.", "synergy": ["field_medic_kit", "speed"]},
	"lucky_shrapnel": {"title": "+ LUCKY SHRAPNEL", "tag": "LUCK", "hint": "Adds extra shells and explosion damage after Lucky Core.", "synergy": ["lucky_core", "splash"]},
	"gravity_fins": {"title": "+ GRAVITY FINS", "tag": "CONTROL", "hint": "Adds shell speed and area damage after Gravity Anchor.", "synergy": ["gravity_anchor", "accelerator"]},
	"reinforced_ammo_belt": {"title": "+ REINFORCED AMMO BELT", "tag": "MULTISHOT", "hint": "Slightly improves fire cadence and extra-shell chance after Fire Rate.", "synergy": ["fire_rate", "cannon"]},
	"crystal_reservoir": {"title": "+ CRYSTAL RESERVOIR", "tag": "ECONOMY", "hint": "Raises EXP value and pickup reach after EXP Value.", "synergy": ["exp", "magnet"]},
	"storm_insulator": {"title": "+ STORM INSULATOR", "tag": "POWER", "hint": "Adds armor and power damage after Volt Coils.", "synergy": ["volt_coils", "armor"]},
	"target_predictor": {"title": "+ TARGET PREDICTOR", "tag": "CRIT", "hint": "Adds crit chance and shell speed after Targeting Array.", "synergy": ["targeting_array", "accelerator"]},
	"emergency_battery": {"title": "+ EMERGENCY BATTERY", "tag": "SUSTAIN", "hint": "Adds max health, power damage, and healing after Overdrive Core.", "synergy": ["overdrive_core_level", "nanobots"]},
	"singularity_lens": {"title": "+ SINGULARITY LENS", "tag": "POWER", "hint": "Greatly improves area damage, pickup reach, and power damage after Black Hole Mines.", "synergy": ["black_hole_mines"]},

	}
